services:
    - type: web
      name: tmx-twig
      env: docker
      dockerfilePath: ./Dockerfile
      plan: free
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_DEBUG
            value: "0"
          - key: APP_SECRET
            generateValue: true # Render will generate this
          - key: DATABASE_URL
            fromDatabase:
                name: twig-db # Your Render database name
                property: connectionString
